### ISSUE TITLE
[JENKINS-66770] Cannot update Jenkins server 2.263.3 to latest

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/update-sites-manager-plugin#66]
<p>I currently have Jenkins 2.263.3 and need to update it to the latest version but cannot do it for  a couple of month. When I run the update it says it was successful but when I try to access it after the update it gives me errors and I have to go back to 2.263.3</p>

<p>Here is the error log that it gives me:</p>

<pre>
java.lang.IllegalStateException: An attempt to save the global configuration was made before it was loaded
    at jenkins.model.Jenkins.save(Jenkins.java:3461)
    at jenkins.model.Jenkins.saveQuietly(Jenkins.java:3480)
    at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2707)
    at jenkins.model.Jenkins$15.run(Jenkins.java:3423)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:1160)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
Caused: org.jvnet.hudson.reactor.ReactorException
    at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
    at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
    at jenkins.model.Jenkins.executeReactor(Jenkins.java:1193)
    at jenkins.model.Jenkins.<init>(Jenkins.java:991)
    at hudson.model.Hudson.<init>(Hudson.java:86)
    at hudson.model.Hudson.<init>(Hudson.java:82)
    at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
    at hudson.WebAppMain$3.run(WebAppMain.java:315)
</pre>

<p> </p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/lubap.svg" title="lubap's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=lubap">lubap</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-66770" target="_blank">Cannot update Jenkins server 2.263.3 to latest</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: update-sites-manager-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20260220-165852
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I currently have Jenkins 2.263.3 and need to update it to the latest version but cannot do it for  a couple of month. When I run the update it says it was successful but when I try to access it after the update it gives me errors and I have to go back to 2.263.3</p>

<p>Here is the error log that it gives me:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IllegalStateException: An attempt to save the global configuration was made before it was loaded
    at jenkins.model.Jenkins.save(Jenkins.java:3461)
    at jenkins.model.Jenkins.saveQuietly(Jenkins.java:3480)
    at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2707)
    at jenkins.model.Jenkins$15.run(Jenkins.java:3423)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:1160)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.<span class="code-object">Thread</span>.run(Unknown Source)
Caused: org.jvnet.hudson.reactor.ReactorException
    at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
    at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
    at jenkins.model.Jenkins.executeReactor(Jenkins.java:1193)
    at jenkins.model.Jenkins.&lt;init&gt;(Jenkins.java:991)
    at hudson.model.Hudson.&lt;init&gt;(Hudson.java:86)
    at hudson.model.Hudson.&lt;init&gt;(Hudson.java:82)
    at hudson.WebAppMain$3.run(WebAppMain.java:298)
Caused: hudson.util.HudsonFailedToLoad
    at hudson.WebAppMain$3.run(WebAppMain.java:315)
</pre>
</div></div>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Windows</code></li></ul>

**Comment by slide** [comment]
Not an issue with update-sites-manager plugin.
